# -*- coding: utf-8 -*-
"""Arvores_de_descisao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mW8fnJBexEfAM-J8IgW9VmAgTZV_tnbm
"""

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import matplotlib.pyplot as plt

# Carregando o conjunto de dados iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

# Criando o modelo de árvore de decisão
modelo_arvore = DecisionTreeClassifier()
modelo_arvore.fit(df.iloc[:, :-1], df.iloc[:, -1])

# Visualizando a árvore de decisão
fig = plt.figure(figsize=(15, 10))
arv= tree.plot_tree(modelo_arvore, feature_names=iris.feature_names, class_names=iris.target_names, filled=True)